### ISSUE TITLE
Spelling error in .ioc file

### ISSUE THREAD

**Issue by mattkefford** [STMicroelectronics/STM32CubeF0#13]
The setup: anything that uses .ioc file used by CubeIDE.

I noticed in the CubeF0 1.11.3 changes that you'd corrected a lot of spelling mistakes so I thought it may be a good time to point this one out too :) 

![image](https://user-images.githubusercontent.com/15934099/132040513-63f41d73-b346-4ea4-a9e3-2a66202af508.png)

**Comment by RKOUSTM** [comment]
Hi @mattkefford,

Thank you for your reports. Unfortunately we don't treat aspect related to CubeMx tool in our GitHub repositories. They are rather treated at the [STM32CubeMX](https://community.st.com/s/topic/0TO0X000000BTr8WAG/stm32cubemx) dedicated page of the **ST Community**.  There, you may find posts that already raised the issue you are pointing out here. Otherwise, you can create a new post to submit your issue.  There you shall find people who will address your request and whom you will hopefully find a solution with.


Since this issue is not directly related to the STM32Cube firmware but rather to our ecosystem, please allow me then to close this thread. Thank you again for your report. We are looking forward to reading from you again.

With regards,
